"""Tests for ResNet-like CNN models generated by the test fixture."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import pytest

import litert_tunner
from litert_tunner import testing_utils

if TYPE_CHECKING:
    from collections.abc import Callable


@pytest.mark.parametrize("optimization", ["int8", "float32"])
def test__make_resnet_tflite_creates_valid_model(
    make_resnet_tflite: Callable,
    run_interpreter: Callable,
    optimization: str,
) -> None:
    """Verify that make_resnet_tflite creates a valid, executable TFLite model."""
    input_shape = (8, 8, 3)
    model_path = make_resnet_tflite(
        input_shape=input_shape,
        filters=[8, 16],
        kernel_size=3,
        use_bias=True,
        activation="relu",
        float_io=True,
        add_skip_connections=True,
        add_batchnorm=True,
        pooling_type="max",
        optimization=optimization,
    )

    rng = np.random.default_rng(42)
    x_train = rng.uniform(-1.0, 1.0, (32, 8, 8, 3)).astype(np.float32)
    litert_outputs = run_interpreter(model_path, x_train)

    # compare original LiteRT model with keras parsed
    keras_model = litert_tunner.load_model(str(model_path))
    keras_outputs = keras_model.predict(x_train)
    testing_utils.assert_cosine_similarity(keras_outputs, litert_outputs)

    # outputs are normalized to -1, 1
    max_value = np.abs(litert_outputs).max()
    np.testing.assert_allclose(
        litert_outputs / max_value, keras_outputs / max_value, atol=testing_utils.QUANT_STEP
    )

    # save the model and make sure the outputs are still the same
    litert_tunner.save_model(keras_model, str(model_path))
    litert_saved_outputs = run_interpreter(model_path, x_train)
    np.testing.assert_allclose(litert_outputs, litert_saved_outputs, atol=1e-5)
