"""Tests for ResNet-like CNN models generated by the test fixture."""

from __future__ import annotations

from pathlib import Path
from typing import Callable

import numpy as np
from ai_edge_litert.interpreter import Interpreter


def test__make_resnet_tflite_creates_valid_model(
    make_resnet_tflite: Callable,
    run_interpreter: Callable,
) -> None:
    """Verify that make_resnet_tflite creates a valid, executable TFLite model."""
    input_shape = (8, 8, 3)
    model_path = make_resnet_tflite(
        input_shape=input_shape,
        filters=[8, 16],
        kernel_size=3,
        use_bias=True,
        activation="relu",
        float_io=False,
        add_skip_connections=True,
        add_batchnorm=True,
    )

    assert Path(model_path).exists()

    # Load with interpreter and check details
    interpreter = Interpreter(model_path=str(model_path))
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Verify input shape (batch dimension of 1 is prepended during resizing/run)
    assert input_details[0]["shape"].tolist() == [1, 8, 8, 3]
    assert input_details[0]["dtype"] == np.int8

    # Verify output shape and type
    assert output_details[0]["shape"].tolist() == [1, 10]
    assert output_details[0]["dtype"] == np.int8

    # Run interpreter on random inputs to verify execution
    inputs = np.random.uniform(-1.0, 1.0, (1, 8, 8, 3)).astype(np.float32)
    output = run_interpreter(model_path, inputs)

    assert output.shape == (1, 10)
    assert output.dtype == np.int8
