"""Tests for ConvNeXt models generated by the test fixture."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

import litert_tunner

if TYPE_CHECKING:
    from collections.abc import Callable


def test__make_convnext_tiny_tflite_creates_valid_model(
    make_backbone_tflite: Callable,
    run_interpreter: Callable,
) -> None:
    """Verify that make_backbone_tflite creates a valid, executable ConvNeXtTiny TFLite model."""
    input_shape = (96, 96, 3)
    # Using weights=None to avoid network dependency in tests
    model_path = make_backbone_tflite(
        input_shape=input_shape,
        weights=None,
        num_outputs=100,
        float_io=True,
        backbone_name="ConvNeXtTiny",
    )

    rng = np.random.default_rng(42)
    # Use a small batch size for quick verification
    x_train = rng.uniform(-1.0, 1.0, (4, 96, 96, 3)).astype(np.float32)
    litert_outputs = run_interpreter(model_path, x_train)

    # Compare original LiteRT model with Keras parsed
    keras_model = litert_tunner.load_model(str(model_path))
    keras_outputs = keras_model.predict(x_train)
    np.testing.assert_allclose(litert_outputs, keras_outputs, atol=0.001)

    # Save the model and make sure the outputs are still the same
    litert_tunner.save_model(keras_model, str(model_path))
    litert_saved_outputs = run_interpreter(model_path, x_train)
    np.testing.assert_allclose(keras_outputs, litert_saved_outputs, atol=0.001)
