"""Tests for EfficientNetB0 models generated by the test fixture."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

import litert_tunner
from litert_tunner import testing_utils

if TYPE_CHECKING:
    from collections.abc import Callable


def test__make_efficientnetb0_tflite_creates_valid_model(
    make_efficientnetb0_tflite: Callable,
    run_interpreter: Callable,
) -> None:
    """Verify that make_efficientnetb0_tflite creates a valid, executable TFLite model."""
    input_shape = (32, 32, 3)
    # Using weights=None to avoid network dependency in tests
    model_path = make_efficientnetb0_tflite(
        input_shape=input_shape,
        weights=None,
        num_outputs=100,
        float_io=True,
    )

    rng = np.random.default_rng(42)
    # Use a small batch size for quick verification
    x_train = rng.uniform(-1.0, 1.0, (2, 32, 32, 3)).astype(np.float32)
    litert_outputs = run_interpreter(model_path, x_train)

    # Compare original LiteRT model with Keras parsed
    keras_model = litert_tunner.load_model(str(model_path))
    keras_outputs = keras_model.predict(x_train)
    testing_utils.assert_cosine_similarity(keras_outputs, litert_outputs)

    # outputs are normalized to -1, 1
    max_value = np.abs(litert_outputs).max()
    np.testing.assert_allclose(litert_outputs / max_value, keras_outputs / max_value, atol=0.001)

    # Save the model and make sure the outputs are still the same
    litert_tunner.save_model(keras_model, str(model_path))
    litert_saved_outputs = run_interpreter(model_path, x_train)
    np.testing.assert_allclose(litert_outputs, litert_saved_outputs, atol=1e-5)
